services:
  digital-zone:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=digital-zone
    command:
      [
        'sh',
        '-c',
        'npx prisma generate --schema=./apps/digital-zone/prisma/schema.prisma && npm run start:dev -- digital-zone',
      ]
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=digital-zone-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
      - DATABASE_URL=postgresql://postgres:postgres@digital-zone-db:5432/products
      - API_KEY=api-secret-key
      - DATA_FETCH_INTERVAL=5000
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/digital-zone:/usr/src/app/apps/digital-zone
      - ./apps/digital-zone/client:/usr/src/app/client
  digital-zone-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    volumes:
      - ./pg_data/db-zone:/var/lib/postgresql/data
      - ./initial-data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  provider-one:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=provider-one
    command:
      [
        'sh',
        '-c',
        'npx prisma generate --schema=./apps/provider-one/prisma/schema.prisma && npm run start:dev -- provider-one',
      ]
    ports:
      - 3001:3001
    environment:
      - POSTGRES_HOST=digital-zone-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=provider-one-db
      - DATABASE_URL=postgresql://postgres:postgres@digital-zone-db:5432/provider-one-db
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/provider-one:/usr/src/app/apps/provider-one
    depends_on:
      - digital-zone-db

  provider-two:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=provider-two
    command:
      [
        'sh',
        '-c',
        'npx prisma generate --schema=./apps/provider-two/prisma/schema.prisma && npm run start:dev -- provider-two',
      ]
    ports:
      - 3002:3002
    environment:
      - POSTGRES_HOST=digital-zone-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=provider-two-db
      - DATABASE_URL=postgresql://postgres:postgres@digital-zone-db:5432/provider-two-db
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/provider-two:/usr/src/app/apps/provider-two
    depends_on:
      - digital-zone-db
  provider-three:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=provider-three
    command:
      [
        'sh',
        '-c',
        'npx prisma generate --schema=./apps/provider-three/prisma/schema.prisma && npm run start:dev -- provider-three',
      ]
    ports:
      - 3003:3003
    environment:
      - POSTGRES_HOST=digital-zone-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=provider-three-db
      - DATABASE_URL=postgresql://postgres:postgres@digital-zone-db:5432/provider-three-db
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/provider-three:/usr/src/app/apps/provider-three
    depends_on:
      - digital-zone-db
volumes:
  pg_data:
